#!/bin/sh

mpv "$@" --term-playing-msg='Title: ${media-title}' --script-opts=ytdl-format='bestvideo[height<=?1080][fps<=?30][vcodec!=?vp9]+bestaudio/best' --idle=once --scripts="../audioassistant-mpv" --ytdl-raw-options="no-check-certificate="
